#!/usr/bin/env bash
#
# generateTestThemes.sh
#
# Genera due temi "ciccioni" (uno pubblico, uno admin) pronti da inizializzare
# come repo git e pushare su GitHub, per testare visivamente la barra di
# progress dell'installazione tema da repo Git remoto.
#
# Ogni tema contiene:
#   - Struttura minima valida (themeConfig.json5, themeDescription.json5, views/)
#   - 1 blob binario incompressibile da 5 MB (rallenta la fase 'Receiving objects'
#     facendo avanzare la percentuale e il contatore bytes in modo visibile)
#   - 200 piccoli file (rallentano la fase 'Updating files' producendo molti
#     update X/200 del contatore checkout)
#
# Risultato atteso al clone via 'git clone --progress': barra visibile per
# ~2-3 secondi su rete domestica, con transizione visibile tra gli stadi.
#
# Naming (convenzione del modulo themesInstall):
#   Repo:    ital8cms-theme-themePublicForTest  →  cartella: themePublicForTest
#   Repo:    ital8cms-theme-themeAdminForTest   →  cartella: themeAdminForTest
#
# Nota: il modulo applica kebabToCamel al segmento dopo "ital8cms-theme-",
# ma se il segmento è già camelCase (nessun dash) la conversione è un no-op
# e il segmento viene usato così com'è come nome cartella.
#
# Usage:
#   bash scripts/generateTestThemes.sh [outputDir]
#   (default outputDir: ./test-themes-output)

set -euo pipefail

OUT_DIR="${1:-./test-themes-output}"
BLOB_SIZE_MB=5
SMALL_FILES_COUNT=200

# ----- helpers -------------------------------------------------------------

c_green=$'\033[32m'
c_cyan=$'\033[36m'
c_yellow=$'\033[33m'
c_reset=$'\033[0m'

info()  { printf "${c_cyan}[info]${c_reset} %s\n" "$*"; }
ok()    { printf "${c_green}[ok]${c_reset}   %s\n" "$*"; }
warn()  { printf "${c_yellow}[warn]${c_reset} %s\n" "$*"; }

# ----- generators ----------------------------------------------------------

write_theme_config() {
    local theme_dir="$1"
    local is_admin="$2"
    cat > "$theme_dir/themeConfig.json5" <<EOF
// This file follows the JSON5 standard - comments and trailing commas are supported
{
  // 'active' e 'isInstalled' vengono comunque forzati a 0 dal modulo
  // themesInstall durante l'installazione: i valori qui sono solo orientativi.
  "active": 0,
  "isInstalled": 0,
  "weight": 100,
  "isAdminTheme": $is_admin,
  "pluginDependency": {},
}
EOF
}

write_theme_description() {
    local theme_dir="$1"
    local theme_name="$2"
    local description="$3"
    cat > "$theme_dir/themeDescription.json5" <<EOF
// This file follows the JSON5 standard - comments and trailing commas are supported
{
  "name": "$theme_name",
  "version": "1.0.0",
  "description": "$description",
  "author": "Italo Paesano",
  "email": "italopaesano@protonmail.com",
  "license": "ISC",
}
EOF
}

write_views() {
    local theme_dir="$1"
    local theme_name="$2"

    cat > "$theme_dir/views/head.ejs" <<'EOF'
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= typeof title !== 'undefined' ? title : 'Test Theme' %></title>
  <%- await pluginSys.hookPage("head", passData) %>
</head>
EOF

    cat > "$theme_dir/views/header.ejs" <<EOF
<header>
  <h1>$theme_name</h1>
  <%- await pluginSys.hookPage("header", passData) %>
</header>
EOF

    cat > "$theme_dir/views/footer.ejs" <<'EOF'
<footer>
  <small>Test theme — generated by generateTestThemes.sh</small>
  <%- await pluginSys.hookPage("script", passData) %>
</footer>
EOF
}

write_readme() {
    local theme_dir="$1"
    local theme_name="$2"
    local kind="$3"
    cat > "$theme_dir/README.md" <<EOF
# $theme_name

Tema $kind di test, generato da \`generateTestThemes.sh\`.

Volutamente "ciccione" (~7 MB) per rendere visibile la barra di progress
dell'installazione tema da repo Git nel pannello admin di ital8cms.

Non usare in produzione.
EOF
}

write_gitignore() {
    local theme_dir="$1"
    cat > "$theme_dir/.gitignore" <<'EOF'
.DS_Store
*.tmp
node_modules/
EOF
}

generate_fat_payload() {
    local theme_dir="$1"

    mkdir -p "$theme_dir/themeResources/blob" "$theme_dir/themeResources/assets"

    info "  generating ${BLOB_SIZE_MB}MB incompressible blob (urandom)..."
    dd if=/dev/urandom of="$theme_dir/themeResources/blob/payload.bin" \
       bs=1M count=$BLOB_SIZE_MB status=none

    info "  generating $SMALL_FILES_COUNT small files (for 'Updating files' stage)..."
    # Genera una pool di contenuto random una volta sola e la spezzetta.
    local pool
    pool=$(head -c $(( SMALL_FILES_COUNT * 200 )) /dev/urandom | base64)
    local pool_len=${#pool}
    local chunk=200
    for i in $(seq 1 $SMALL_FILES_COUNT); do
        printf -v idx "%04d" "$i"
        local offset=$(( (i - 1) * chunk % (pool_len - chunk) ))
        local content="${pool:$offset:$chunk}"
        printf 'File %s\n%s\n' "$idx" "$content" \
            > "$theme_dir/themeResources/assets/file-$idx.txt"
    done
}

# ----- main ----------------------------------------------------------------

create_theme() {
    local theme_name="$1"      # nome cartella (camelCase, va in themeDescription.name)
    local is_admin="$2"        # "true" oppure "false"
    local repo_segment="$3"    # kebab-case da usare nel nome del repo GitHub
    local kind="$4"            # "pubblico" oppure "admin" — per la doc

    local theme_dir="$OUT_DIR/$theme_name"

    info "Generating theme '$theme_name' (isAdminTheme=$is_admin) → $theme_dir"

    if [ -e "$theme_dir" ]; then
        warn "  $theme_dir esiste già: lo rimuovo prima di ricrearlo."
        rm -rf "$theme_dir"
    fi

    mkdir -p "$theme_dir/views"

    write_theme_config "$theme_dir" "$is_admin"
    write_theme_description "$theme_dir" "$theme_name" \
        "Tema $kind di test per la barra di progress (volutamente ciccione)."
    write_views "$theme_dir" "$theme_name"
    write_readme "$theme_dir" "$theme_name" "$kind"
    write_gitignore "$theme_dir"
    generate_fat_payload "$theme_dir"

    local size
    size=$(du -sh "$theme_dir" | cut -f1)
    ok "  Tema '$theme_name' pronto ($size). Repo GitHub atteso: ital8cms-theme-$repo_segment"
}

main() {
    mkdir -p "$OUT_DIR"
    info "Output dir: $OUT_DIR"
    info "Config: blob=${BLOB_SIZE_MB}MB, small files=$SMALL_FILES_COUNT"
    echo

    create_theme \
        "themePublicForTest" \
        "false" \
        "themePublicForTest" \
        "pubblico"
    echo

    create_theme \
        "themeAdminForTest" \
        "true" \
        "themeAdminForTest" \
        "admin"
    echo

    cat <<EOF
${c_green}Generazione completata.${c_reset}

Prossimi passi per ognuno dei due temi:

  cd $OUT_DIR/themePublicForTest
  git init
  git add .
  git commit -m "Initial commit: dummy public theme for progress bar testing"
  git branch -M main
  # Crea il repo su GitHub con nome 'ital8cms-theme-themePublicForTest'
  git remote add origin https://github.com/<USER>/ital8cms-theme-themePublicForTest.git
  git push -u origin main

  cd $OUT_DIR/themeAdminForTest
  git init
  git add .
  git commit -m "Initial commit: dummy admin theme for progress bar testing"
  git branch -M main
  # Crea il repo su GitHub con nome 'ital8cms-theme-themeAdminForTest'
  git remote add origin https://github.com/<USER>/ital8cms-theme-themeAdminForTest.git
  git push -u origin main

Poi nel pannello admin ital8cms (/admin/themesManagment/install.ejs) inserisci:
  https://github.com/<USER>/ital8cms-theme-themePublicForTest.git
oppure:
  https://github.com/<USER>/ital8cms-theme-themeAdminForTest.git

Nota: il push di ~7MB su GitHub può richiedere qualche secondo a seconda
della banda in upload. Il clone dal pannello admin di ital8cms invece
mostrerà la barra di progress per circa 2-3 secondi su connessione fibra.
EOF
}

main "$@"
